# Generated by Django 5.1.1 on 2024-09-08 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10, unique=True)),
                ('max_vms', models.PositiveIntegerField()),
                ('max_backups', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='billing_profile',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='children',
            field=models.ManyToManyField(related_name='billing_profile_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.billingprofile')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.rateplan')),
            ],
        ),
    ]
