# Generated by Django 5.1.1 on 2024-09-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_billingprofile_children_remove_invoice_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingprofilechild',
            options={'verbose_name': 'Child Billing Account'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
    ]
