# Generated by Django 5.1.1 on 2024-09-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_billingprofilechild_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='rate_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.rateplan'),
        ),
    ]
