# Generated by Django 5.1.1 on 2024-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_subscription_rate_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofilechild',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
