services:
  frontend:
    build:
      context: ./hynfra_web
      dockerfile: Dockerfile
    expose:
      - "80"
  django:
    build:
      context: ./hynfra_api
      dockerfile: Dockerfile

    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./hynfra_nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - frontend
      - django

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"

volumes:
  postgres_data:
  django-static:
  vue-dist:
