
services:
  django:
    image: nguthiru/hynfra-api:latest
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"

volumes:
  postgres_data:

  vue-dist: