
services:
  frontend:
    image: nguthiru/hynfra-web:latest
    ports:
      - "8080:80"
    volumes:
      - vue-dist:/app/dist
    
  django:
    image: nguthiru/hynfra-api:latest
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nguthiru/hynfra-nginx:latest
    ports:
      - "80:80"
    volumes:
      - vue-dist:/usr/share/nginx/html

    depends_on:
      - frontend

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"

volumes:
  postgres_data:
  vue-dist: