apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: django-staticfiles-pvc

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 
  volumeName: django-staticfiles-pv
  
