apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hynfra-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: django
            port: 
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port: 
              number: 80