apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.service.expose: example.com
    kompose.service.type: loadbalancer
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s/
        kompose.service.expose: example.com
        kompose.service.type: loadbalancer
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nguthiru/hynfra-nginx:latest
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: vue-dist
            - mountPath: /etc/nginx/conf.d
              name: nginx-claim1
      restartPolicy: Always
      volumes:
        - name: vue-dist
          persistentVolumeClaim:
            claimName: vue-dist
        - name: nginx-claim1
          persistentVolumeClaim:
            claimName: nginx-claim1
