apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: vue-dist
  name: vue-dist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
