# Generated by Django 5.1.1 on 2024-09-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='VirtualMachineBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.virtualmachine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
