# Generated by Django 5.1.1 on 2024-09-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_virtualmachine_updated_at_virtualmachinebackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='cpu_core_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ram_size_gb',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('deleted', 'Deleted'), ('paused', 'Paused')], default='created', max_length=100),
        ),
    ]
