# Generated by Django 5.1.1 on 2024-09-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_virtualmachine_cpu_core_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='ip_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
