# Generated by Django 5.1.1 on 2024-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_virtualmachine_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachinebackup',
            name='backup_size',
            field=models.FloatField(blank=True, help_text='Size of the backup in GB', null=True),
        ),
        migrations.AddField(
            model_name='virtualmachinebackup',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress')], default='created', max_length=100),
        ),
    ]
