name: Update Server with New Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Ssh Into Server and Update Frontend
        run: |
          sshpass -p "${{ secrets.VM_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.VM_SSH_PORT }} ${{ secrets.VM_SSH_USERNAME }}@${{ secrets.VM_SSH_HOST }} 'bash -l -c "
            cd ~/hynfra_vm_management/ && \
            git pull && \
            cd hynfra_web && \
            source ~/.bashrc && \
            npm install && \
            npm run build && \
            sudo cp -r dist/* /var/www/html/ && \
            sudo systemctl restart nginx
          "'
