name: Django + Vue Build and Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and Push Django Docker Image
      - name: Build and push Django Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hynfra-api:latest -f ./hynfra_api/Dockerfile ./hynfra_api
          docker push ${{ secrets.DOCKER_USERNAME }}/hynfra-api:latest

      # Build and Push Vue Docker Image
      - name: Build and push Vue Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hynfra-web:latest -f ./hynfra_web/Dockerfile ./hynfra_web
          docker push ${{ secrets.DOCKER_USERNAME }}/hynfra-web:latest
      - name: Build and push Nginx Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hynfra-nginx:latest -f ./hynfra_nginx/Dockerfile ./hynfra_nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/hynfra-nginx:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      
      - name: Ssh Into Server and Update Kubernetees Deployment
        run: |
          sshpass -p "${{ secrets.VM_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.VM_SSH_PORT }} ${{ secrets.VM_SSH_USERNAME }}@${{ secrets.VM_SSH_HOST }} 'bash -l -c "
            cd ~/hynfra_vm_management/ && \
            git pull && \
            microk8s.kubectl apply -f k8s/ && \
            microk8s.kubectl set image deployment/frontend frontend=nguthiru/hynfra-web:latest && \
            microk8s.kubectl set image deployment/django django=nguthiru/hynfra-api:latest && \
            microk8s.kubectl set image deployment/nginx nginx=nguthiru/hynfra-nginx:latest

          "'


      


        
